version: '3.8'

services:
  songbook:
    image: songbook-tlk
    container_name: songbook-tlk
    restart: unless-stopped
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/sangbok/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - songbook-network

networks:
  songbook-network:
    driver: bridge 