name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Create a clean deployment directory
      - name: Create deployment directory
        run: |
          mkdir deploy
          cp index.html deploy/
          cp styles.css deploy/
          cp script.js deploy/
          cp songView.js deploy/
          cp songs.json deploy/
          cp tlklogo-white.png deploy/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4