name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          echo "Creating deployment directory..."
          cp -v index.html deploy/ || echo "Failed to copy index.html"
          cp -v styles.css deploy/ || echo "Failed to copy styles.css"
          cp -v script.js deploy/ || echo "Failed to copy script.js"
          cp -v songView.js deploy/ || echo "Failed to copy songView.js"
          cp -v songs.json deploy/ || echo "Failed to copy songs.json"
          cp -v tlklogo-white.png deploy/ || echo "Failed to copy tlklogo-white.png"
          ls -la deploy/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3