name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy website files
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          clean: true
          clean-exclude: |
            add_song.py
            *.bak
            songs.json.bak
          files: |
            index.html
            styles.css
            script.js
            songView.js
            songs.json
            tlklogo-white.png
            tlklogo_blue.svg 